language: ruby
rvm:
  #- 1.8.7
  #- 1.9.2
  - 1.9.3
  - ree
  #- rbx-18mode
env:
  - "RAILS_ENV=test DB=mysql BUNDLE_WITHOUT=rmagick:mysql2:postgres:sqlite"
  - "RAILS_ENV=test DB=mysql2 BUNDLE_WITHOUT=rmagick:mysql:postgres:sqlite"
  #- "RAILS_ENV=test DB=postgres BUNDLE_WITHOUT=rmagick:mysql:mysql2:sqlite"
  #- "RAILS_ENV=test DB=sqlite BUNDLE_WITHOUT=rmagick:mysql:mysql2:postgres"
matrix:
  exclude:
    #- rvm: 1.9.2
    #  env: "RAILS_ENV=test DB=mysql BUNDLE_WITHOUT=rmagick:mysql2:postgres:sqlite"
    - rvm: 1.9.3
      env: "RAILS_ENV=test DB=mysql BUNDLE_WITHOUT=rmagick:mysql2:postgres:sqlite"
    #- rvm: rbx-18mode
    #  env: "RAILS_ENV=test DB=mysql BUNDLE_WITHOUT=rmagick:mysql2:postgres:sqlite"
  allow_failures:
    - rvm: ree
before_script:
  - "sudo apt-get --no-install-recommends install bzr cvs darcs git mercurial subversion"
  - "git submodule update --init --recursive"
  - "rake ci:travis:prepare" # includes db:migrate:plugins
branches:
  only:
    - unstable
    - master
    - stable
    - /^stable-.*$/
    - /^release-.*$/
notifications:
  email: false
