language: ruby
rvm:
  - 1.9.3
#  - 1.9.2
before_install:
  - git submodule update --init --recursive
bundler_args: --without postgres sqlite
before_script:
  - cp config/database.mysql.yml config/database.yml
  - bundle exec rake ci:setup
