test:
  adapter: mysql2
  database: chiliproject_test
  host: 127.0.0.1
  username: root
  password:
  encoding: utf8

test_pgsql:
  adapter: postgresql
  database: chiliproject_test
  host: localhost
  username: postgres
  password: "postgres"

test_sqlite3:
  adapter: sqlite3
  database: db/test.sqlite3
